services:
  - type: web
    name: rainwater-harvesting-app
    env: python
    plan: free
    buildCommand: |
      # Install Python dependencies
      pip install -r requirements-prod.txt
      # Build frontend
      python build_frontend.py
    startCommand: python backend.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
    healthCheckPath: /
